### ISSUE TITLE
Add tests and travis support

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-tutorials-samples#44]
Would be great to ensure these stay working with Dart v2

**Comment by kwalrath** [comment]
And remove all references to drone.io.

**Comment by jddeep** [comment]
@kevmoo @kwalrath Would love to add the travis-ci support checks for this repo. Could I go ahead?

**Comment by kevmoo** [comment]
If you want to try!

I'd recommend setting up https://pub.dev/packages/mono_repo – should make things a lot easier!

**Comment by kwalrath** [comment]
Actually... I believe we plan to move everything from dart-tutorials-samples to either site-www or samples. So it'd be good to have tests in that destination repo, once each sample moves.

**Comment by jddeep** [comment]
Then I believe we can close this issue here atm.
