### ISSUE TITLE
Move `helloworld` to site-www repo

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-tutorials-samples#55]
The helloworld example is actually referenced from the cmdline tutorial page. Is there a reason that the project is at the top level @kwalrath?

**Comment by kwalrath** [comment]
No idea... Go ahead and move it if that's what makes sense.

**Comment by kwalrath** [comment]
Thinking about this some more... we now have a https://github.com/dart-lang/samples repo. I wonder if the contents of this repo should move there.

/cc @mit-mit @johnpry

**Comment by chalin** [comment]
I'm in the process of moving the cmdline/dcat code to site-www (simply because it is easier to manage with the added tooltips and code-excerpt tags). So maybe there are apps/packages that can simply be dropped from here?

**Comment by chalin** [comment]
@kwalrath, I think that you meant to cc @johnpryan (I can't edit your original comment to fix that so I'm cc'ing John here.)

**Comment by jddeep** [comment]
> Thinking about this some more... we now have a https://github.com/dart-lang/samples repo. I wonder if the contents of this repo should move there.
> 
> /cc @mit-mit @johnpryan

@kwalrath Could I get on with it?

**Comment by kwalrath** [comment]
Sorry for the delay, @jddeep — I just saw this.

You should probably work with @johnpryan on this. @johnpryan, what do you say?

**Comment by kwalrath** [comment]
@mit-mit could you add @johnpryan to this repo? I can't assign this issue to him.

**Comment by johnpryan** [comment]
I agree any samples we intend to support should move to dart-lang/samples or site-www. We effectively have a hello-world app [in dart-lang/samples](https://github.com/dart-lang/samples/tree/master/native_app), but it's called "native_app" and has instructions for using `dart2native`. 

I think in this case it makes sense to have `dcat` and `helloworld` grouped together under `cmdline` and moved to site-www`.

**Comment by kwalrath** [comment]
It looks like we do have dcat at https://github.com/dart-lang/site-www/blob/master/examples/misc/bin/dcat.dart.

We don't, however, have helloworld code on site-www.

**Comment by kwalrath** [comment]
@jddeep we'd be very happy for you to fix this with PRs in this repo and in site-www. Thank you for the offer!

**Comment by jddeep** [comment]
@kwalrath Cool am on it.

**Comment by mit-mit** [comment]
@johnpryan you now have write rights.

**Comment by jddeep** [comment]
@kwalrath Should I make a PR here cleaning up the `helloworld` sample from here? Cause it has been already made present in `site-www` repo earlier.
Do let me know. Thanks.

**Comment by kwalrath** [comment]
@jddeep yes, please!
